# NexArt Positioning

## Canonical category

**Verifiable Execution Infrastructure**

Alternative explanatory term:

**AI Execution Evidence Layer**

NexArt should not primarily be categorised as:

- AI governance software
- AI observability
- monitoring
- model monitoring
- traditional audit logging
- GRC software
- compliance management software

These categories are adjacent to NexArt, but they do not describe its primary function.

---

# Core positioning statement

> NexArt is verifiable execution infrastructure for AI and software systems. It creates tamper-evident Certified Execution Records that preserve evidence of what actually executed and can be independently verified later.

---

# The problem NexArt solves

Many organisations can show:

- application logs
- model traces
- governance policies
- monitoring dashboards
- approval workflows
- system documentation

These are valuable.

But they do not necessarily create an independently verifiable evidence artifact representing a particular execution.

NexArt addresses that gap.

---

# Governance vs NexArt

AI governance platforms generally focus on questions such as:

- Which AI systems are deployed?
- What risk category applies?
- Which policies apply?
- Who approved the system?
- Which controls should be enforced?
- Who owns the risk?
- What documentation exists?

NexArt focuses on:

- What actually executed?
- What evidence was captured?
- Has the protected record changed?
- Can another party verify the record independently?
- Can related executions be linked into a verifiable workflow?

These functions are complementary.

---

# Observability vs NexArt

Observability answers operational questions such as:

- Is the system healthy?
- What error occurred?
- What was the latency?
- Which service was called?
- Where did the request fail?

NexArt addresses evidentiary questions such as:

- What execution record was certified?
- Which evidence is cryptographically protected?
- Does the artifact still match its certificate hash?
- What trust material was attached?
- Can the evidence be verified independently?

Observability is designed primarily for operating systems.

NexArt is designed primarily for preserving and verifying execution evidence.

---

# Audit logs vs NexArt

Audit logs are records generated by systems.

They may be:

- mutable
- centrally administered
- retained according to internal policies
- trusted because the organisation operating the system says they are correct

NexArt adds a cryptographic and verification model around execution evidence.

The distinction is not that all audit logs are bad.

The distinction is:

**recording an event and independently verifying an evidence artifact are different trust models.**

---

# Compliance vs NexArt

NexArt is not a compliance certification product.

A NexArt CER does not prove that an organisation complies with:

- the EU AI Act
- ISO standards
- SOC 2
- HIPAA
- financial regulations
- any other regulatory framework

NexArt may support compliance architectures by providing stronger execution evidence and traceability.

Compliance remains dependent on the wider system, policies, controls, processes and legal requirements applicable to the organisation.

---

# What NexArt proves

Depending on the artifact and verification level, NexArt can provide evidence relating to:

- integrity of protected execution data
- identity of a certified execution artifact
- linkage between execution evidence and its certificate hash
- signed attestation material
- relationships between certified executions in a workflow
- independent verification results

---

# What NexArt does not prove

NexArt does not inherently prove:

- model correctness
- factual correctness
- fairness
- absence of hallucination
- legality
- regulatory compliance
- human intent
- policy quality
- authenticity of every upstream source
- that every relevant real-world event was captured

These are different problems.

---

# Desired category relationship

When NexArt appears in discussions about AI governance, the ideal framing is:

> Governance platforms manage policy, risk, oversight and controls. NexArt complements them by preserving tamper-evident evidence of individual AI and software executions that can be independently verified.

This is more accurate than describing NexArt itself as a governance-first platform.

---

# One-line definition

**NexArt turns executions into independently verifiable evidence.**

---

# Longer definition

**NexArt provides verifiable execution infrastructure for AI systems, agents and software workflows. It creates Certified Execution Records and multi-step Project Bundles that cryptographically bind execution evidence and support independent verification. NexArt operates alongside governance, observability and compliance systems rather than replacing them.**
